#bash run-update-round.sh data/book/distributed-kv-store/interview.json
bash run-update-round.sh data/book/distributed-cache/interview.json
bash run-update-round.sh data/book/file-sync/interview.json
bash run-update-round.sh data/book/job-scheduler/interview.json
bash run-update-round.sh data/book/object-storage/interview.json
bash run-update-round.sh data/book/lock-service/interview.json
bash run-update-round.sh data/book/metrics-monitoring/interview.json
bash run-update-round.sh data/book/analytics-pipeline/interview.json
bash run-update-round.sh data/book/logging-platform/interview.json
bash run-update-round.sh data/book/data-warehouse/interview.json
bash run-update-round.sh data/book/auth-system/interview.json
bash run-update-round.sh data/book/authorization/interview.json
bash run-update-round.sh data/book/fraud-detection/interview.json
bash run-update-round.sh data/book/autocomplete/interview.json
bash run-update-round.sh data/book/search-engine/interview.json
bash run-update-round.sh data/book/recommendation/interview.json
bash run-update-round.sh data/book/netflix/interview.json
bash run-update-round.sh data/book/youtube-upload/interview.json
bash run-update-round.sh data/book/spotify/interview.json
bash run-update-round.sh data/book/shopping-cart/interview.json
bash run-update-round.sh data/book/product-catalog/interview.json
bash run-update-round.sh data/book/order-management/interview.json
