"""Generate a logo image for each post in a journal using Google's Gemini
image-generation model (gemini-3-pro-image-preview).

Usage:
    GEMINI_API_KEY=... python3 _wiring/generate_logos.py --journal decisions-log

The set of posts to process is taken from the journal's ``config.yaml``
(the same source of truth ``build.py`` uses): every path listed under
``sections[].posts`` is checked. The skip decision is based on the logo
file's presence on disk -- not on the front-matter field -- so a post whose
``logo:`` is set but whose underlying file was deleted will get regenerated.

For each post:

  1. If the logo file exists on disk, skip generation. If the post is
     missing the ``logo:`` (or ``logo_credit:``) front-matter field, wire
     it up.
  2. Otherwise, build a short visual prompt from the post title + excerpt
     + first body paragraphs, call the Gemini image model, and save the
     result to
     ``_journals/<journal>/posts/<slug>/assets/images/logo.jpeg``.
  3. Add the front-matter field(s) if not already there::

         logo: assets/images/logo.jpeg
         logo_credit: "Image generated by Google Gemini (gemini-2.5-flash-image-preview)"

Standard-library only — matches the rest of ``_wiring``.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

# Reuse the journal's own YAML subset parser so we read config.yaml exactly
# the same way build.py does.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build import parse_yaml  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
JOURNALS_DIR = REPO_ROOT / "_journals"

# MODEL = "gemini-3.1-flash-image-preview"
MODEL = "gemini-3-pro-image-preview"

ENDPOINT = (
    "https://generativelanguage.googleapis.com/v1beta/models/"
    f"{MODEL}:generateContent"
)
LOGO_CREDIT = f"Image generated by Google Gemini ({MODEL})"


# ---------- front matter helpers (kept compatible with build.py) ----------

def split_front_matter(text: str):
    """Return (fm_lines, body) where fm_lines is the list of raw lines
    between the leading ``---`` fences. If no front matter is present,
    fm_lines is None."""
    if not text.startswith("---"):
        return None, text
    end = text.find("\n---", 3)
    if end == -1:
        return None, text
    fm = text[3:end].strip("\n")
    body_start = text.find("\n", end + 3)
    body = text[body_start + 1:] if body_start != -1 else ""
    return fm.splitlines(), body


def parse_fm_dict(fm_lines):
    """Parse front matter lines into a dict of stripped string values.
    Mirrors build.parse_front_matter's behavior."""
    meta = {}
    for line in fm_lines or []:
        line = line.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        v = value.strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ('"', "'"):
            v = v[1:-1]
        meta[key.strip()] = v
    return meta


def write_post_with_added_fm(path: Path, fm_lines, body, additions):
    """Append ``additions`` (list of (key, value) pairs) to fm_lines and
    write the file back. Values are written as double-quoted strings."""
    new_fm = list(fm_lines)
    for key, value in additions:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        new_fm.append(f'{key}: "{escaped}"')
    text = "---\n" + "\n".join(new_fm) + "\n---\n" + body
    path.write_text(text, encoding="utf-8")


# ---------- prompt construction ----------

def build_prompt(title: str, excerpt: str, body: str) -> str:
    """Construct an image-generation prompt summarizing the post."""
    # Strip front-matter-free body to first ~500 chars of plain-ish text.
    snippet_lines = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        # Skip headings / fences / image refs to keep prose only.
        if stripped.startswith(("#", "```", "---", "![")):
            continue
        snippet_lines.append(stripped)

    snippet = " ".join(snippet_lines)

    parts = [
        "Create a visual that best illustrates the content of the post. "
        "Text is fine, but not too much -- the image should be primarily visual. "
        "Do not show the article title. "
        "Do not show status or dates. "
        "Style should match a polished business explainer board with flat vector cartoon illustration, crisp outlines, and minimal shading. "
        "include lightweight UI fragments, messages, dashboards, operational artifacts, or support touchpoints where they help explain the stage. "
        "Use disciplined blue, teal, green, and orange accents unless the domain clearly demands something else. "
        "Preserve generous margins so no card, arrow, or label touches the edges. "
        "No photorealism, no 3D render, no fantasy elements, no clip-art collage, no dense text poster. "
    ]
    if excerpt:
        parts.append(f"Excerpt: {excerpt}")
    if snippet:
        parts.append(f"Content snippet: {snippet}")
    return "\n".join(parts)


# ---------- Gemini API call ----------

def call_gemini_image(api_key: str, prompt: str, timeout: int = 240) -> bytes:
    """Call the Gemini image model and return the raw image bytes (JPEG/PNG).
    Raises RuntimeError on failure."""
    payload = {
        "contents": [
            {
                "role": "user",
                "parts": [{"text": prompt}],
            }
        ],
        "generationConfig": {
            "responseModalities": ["IMAGE"],
            "imageConfig": {
                "aspectRatio": "16:9"
            },
        },
    }
    req = urllib.request.Request(
        f"{ENDPOINT}?key={api_key}",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read()
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {e.code} from Gemini: {detail}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"Network error calling Gemini: {e}") from e

    data = json.loads(body.decode("utf-8"))
    candidates = data.get("candidates") or []
    for cand in candidates:
        for part in (cand.get("content") or {}).get("parts") or []:
            inline = part.get("inlineData") or part.get("inline_data")
            if inline and inline.get("data"):
                return base64.b64decode(inline["data"])

    raise RuntimeError(
        "No image data in Gemini response. Raw response: "
        + json.dumps(data)[:1000]
    )


# ---------- main per-post workflow ----------

def _image_paths(journal_dir: Path, post_src: Path):
    """Return (image_path_on_disk, logo_value_for_front_matter).

    Two post layouts are supported. In both cases the image lives under a
    per-slug subfolder so that multiple posts can be merged into the same
    journal-level ``docs/<journal>/assets/images/`` output without colliding.

    1. ``posts/<slug>/index.md`` (decisions-log style) — image at
       ``posts/<slug>/assets/images/<slug>/logo.jpeg``; front matter
       ``logo: assets/images/<slug>/logo.jpeg``. The build merges the
       post-level ``assets/`` into the journal-level output, so the path
       resolves at ``docs/<journal>/assets/images/<slug>/logo.jpeg``.

    2. ``posts/<year>/<slug>.md`` (test/underhood style) — no per-post
       directory; image goes to the journal's shared
       ``assets/images/<slug>/logo.jpeg`` and front matter is
       ``logo: assets/images/<slug>/logo.jpeg``.
    """
    if post_src.name in ("index.md", "index.markdown"):
        post_dir = post_src.parent
        slug = post_dir.name
        return (
            post_dir / "assets" / "images" / slug / "logo.jpeg",
            f"assets/images/{slug}/logo.jpeg",
        )
    slug = post_src.stem
    return (
        journal_dir / "assets" / "images" / slug / "logo.jpeg",
        f"assets/images/{slug}/logo.jpeg",
    )


def process_post(journal_dir: Path, post_src: Path, api_key: str, dry_run: bool) -> str:
    """Returns a short status string for the post."""
    label = post_src.relative_to(journal_dir / "posts").as_posix()

    text = post_src.read_text(encoding="utf-8")
    fm_lines, body = split_front_matter(text)
    if fm_lines is None:
        return f"skip (no front matter): {label}"

    meta = parse_fm_dict(fm_lines)
    image_path, logo_value = _image_paths(journal_dir, post_src)

    if image_path.exists():
        # File on disk is the source of truth. If the front-matter field is
        # already set, leave the post alone; otherwise wire it up.
        if meta.get("logo"):
            return f"skip (logo file present): {label}"
        additions = [("logo", logo_value)]
        if not meta.get("logo_credit"):
            additions.append(("logo_credit", LOGO_CREDIT))
        if not dry_run:
            write_post_with_added_fm(post_src, fm_lines, body, additions)
        return f"linked existing image: {label}"

    title = meta.get("title", post_src.stem)
    excerpt = meta.get("excerpt", "")
    prompt = build_prompt(title, excerpt, body)

    if dry_run:
        return f"dry-run (would generate): {label}"

    print(f"  generating image for: {label} ...", flush=True)
    image_bytes = call_gemini_image(api_key, prompt)
    image_path.parent.mkdir(parents=True, exist_ok=True)
    image_path.write_bytes(image_bytes)

    additions = []
    if not meta.get("logo"):
        additions.append(("logo", logo_value))
    if not meta.get("logo_credit"):
        additions.append(("logo_credit", LOGO_CREDIT))
    if additions:
        write_post_with_added_fm(post_src, fm_lines, body, additions)
    return f"generated: {label}"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--journal",
        required=True,
        help="Journal directory name under _journals/, e.g. decisions-log",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="List what would be done without calling the API or writing files.",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=2.0,
        help="Seconds to sleep between API calls (default: 2.0).",
    )
    args = parser.parse_args(argv)

    journal_dir = JOURNALS_DIR / args.journal
    posts_dir = journal_dir / "posts"
    config_file = journal_dir / "config.yaml"
    if not config_file.is_file():
        print(f"error: no config.yaml at {config_file}", file=sys.stderr)
        return 2
    if not posts_dir.is_dir():
        print(f"error: no posts directory at {posts_dir}", file=sys.stderr)
        return 2

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key and not args.dry_run:
        print(
            "error: GEMINI_API_KEY environment variable is not set.",
            file=sys.stderr,
        )
        return 2

    config = parse_yaml(config_file.read_text(encoding="utf-8")) or {}
    sections = config.get("sections") or []

    # Collect post source files from config.yaml, preserving config order
    # and de-duplicating if a post is listed in multiple sections.
    seen = set()
    targets = []  # list of Path (post source file)
    for section in sections:
        for rel in section.get("posts") or []:
            post_src = posts_dir / rel
            key = post_src.resolve()
            if key in seen:
                continue
            seen.add(key)
            targets.append(post_src)

    print(
        f"Processing {len(targets)} posts from {config_file.relative_to(REPO_ROOT)} ..."
    )

    generated = 0
    missing = 0
    for i, post_src in enumerate(targets):
        label = post_src.relative_to(posts_dir).as_posix()
        if not post_src.exists():
            print(f"[{i + 1}/{len(targets)}] missing post: {label}")
            missing += 1
            continue
        try:
            status = process_post(journal_dir, post_src, api_key, args.dry_run)
        except Exception as e:  # noqa: BLE001 — keep going on per-post errors
            status = f"ERROR ({label}): {e}"
        print(f"[{i + 1}/{len(targets)}] {status}")
        if status.startswith("generated"):
            generated += 1
            if args.sleep and i + 1 < len(targets):
                time.sleep(args.sleep)

    print(f"\nDone. Generated {generated} new image(s).", end="")
    if missing:
        print(f" {missing} post(s) listed in config.yaml were missing on disk.")
    else:
        print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
